export {LandingPage} from './LandingPage/LandingPage'
export {Login} from './Auth/Login'
export {Signup} from './Auth/Signup'
export {Homepage} from './HomePage/Homepage'
export {Archive} from './Archive/Archive'
export {Trash} from './Trash/Trash'
export {Label} from './Label/Label'
export {Profile} from './Profile/Profile'